Repository tektoncd/resolution, pull requests merged in 2022-08, with the labels that each got.

#75 TEP-0115: Add git revision resolution suppot in Git Resolver
  docs/getting-started.md
  gitresolver/README.md
  gitresolver/config/git-resolver-config.yaml
  gitresolver/pkg/git/annotations.go
  gitresolver/pkg/git/config.go
  gitresolver/pkg/git/params.go
  gitresolver/pkg/git/resolver.go
  gitresolver/pkg/git/resolver_test.go
Labels: size/L, approved, lgtm

#76 TEP-0115: Update git resolver doc to use "revision" and "pathInRepo" fields
  gitresolver/README.md
Labels: size/S, approved, lgtm

#78 Fix Broken hubersolver link
  README.md
Labels: approved, lgtm, size/XS

#80 Remove @sbwsg -- account deleted.
  OWNERS
  gitresolver/README.md
Labels: approved, lgtm, size/XS
