Repository tektoncd/resolution, pull requests merged in 2022-04, with the labels that each got.

#24 Add list of resolvers to main README
  README.md
  bundleresolver/README.md
  docs/resolver-template/README.md
  gitresolver/README.md
Labels: kind/documentation, size/M

#25 Remove namespace param from bundle resolver
  bundleresolver/README.md
  bundleresolver/cmd/bundleresolver/main.go
  bundleresolver/pkg/bundle/bundle.go
  bundleresolver/pkg/bundle/params.go
  pkg/common/context.go
  pkg/common/context_test.go
  pkg/resolver/framework/reconciler.go
  tekton/resolution-ci-run.yaml
  tekton/resolution-ci.yaml
  test/bundles_test/bundles_test.go
  test/bundles_test/resolution-request.yaml
Labels: kind/bug, size/L, approved, lgtm

#26 Remove reference to in-progres pipelines PR
  README.md
  bundleresolver/README.md
  docs/getting-started.md
  gitresolver/README.md
  test/e2e-tests.sh
Labels: size/S, kind/documentation

#27 E2E test Tekton Pipelines + Bundle Resolver
  bundleresolver/cmd/bundleresolver/main.go
  bundleresolver/pkg/bundle/params.go
  pkg/resolver/framework/reconciler.go
  test/bundles_test/bundles_test.go
  test/bundles_test/resolution-request.yaml
  test/helpers/read_file_to_object.go
  test/pipeline_bundles_test/pipeline.yaml
  test/pipeline_bundles_test/pipeline_bundles_test.go
  test/pipeline_bundles_test/pipelinerun.yaml
  test/pipeline_bundles_test/pod-tkn-bundle-push.yaml
  test/pipeline_bundles_test/registry-deployment.yaml
  test/pipeline_bundles_test/registry-service.yaml
Labels: size/XL, kind/misc

#29 Add dependabot for gomod updates
  .github/depandabot.yml
Labels: kind/misc, size/XS

#30 Deploy a test registry and bundle before e2e tests
  test/bundle_registry/pipeline.yaml
  test/bundle_registry/registry-deployment.yaml
  test/bundle_registry/registry-service.yaml
  test/e2e-tests.sh
  test/pipeline_bundles_test/pipeline_bundles_test.go
  test/pipeline_bundles_test/pod-tkn-bundle-push.yaml
Labels: size/L, kind/misc

#28 Add hub resolver link to readme
  README.md
Labels: kind/documentation, size/XS

#34 dependabot: fix configuration name
  .github/dependabot.yml
Labels: approved, lgtm, size/XS

#32 Rename "myresolver" to "demoresolver" in docs
  docs/how-to-write-a-resolver.md
  docs/resolver-template/README.md
  docs/resolver-template/cmd/demoresolver/main.go
  docs/resolver-template/config/demo-resolver-deployment.yaml
  docs/resolver-template/test-resolver-template.yaml
  test/smoke_test/resolution-request.yaml
Labels: kind/documentation, size/M

#36 Dependabot notified that zap needs to be updated
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/go.uber.org/zap/.readme.tmpl
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/global.go
  vendor/go.uber.org/zap/global_prego112.go
  vendor/go.uber.org/zap/level.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/stacktrace.go
  vendor/go.uber.org/zap/zapcore/clock.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/level.go
  vendor/go.uber.org/zap/zapcore/reflected_encoder.go
  vendor/go.uber.org/zap/zapcore/sampler.go
  vendor/modules.txt
Labels: size/XL, kind/misc

#37 Document Resolver Types and Example PipelineRuns
  bundleresolver/README.md
  docs/resolver-template/README.md
  gitresolver/README.md
Labels: kind/documentation, size/M

#38 Allow resolvers to watch configmaps and express custom request timeouts
  cmd/controller/main.go
  docs/README.md
  docs/resolver-reference.md
  gitresolver/README.md
  gitresolver/config/git-resolver-config.yaml
  gitresolver/pkg/git/config.go
  gitresolver/pkg/git/resolver.go
  gitresolver/pkg/git/resolver_test.go
  go.mod
  pkg/reconciler/resolutionrequest/controller.go
  pkg/reconciler/resolutionrequest/resolutionrequest.go
  pkg/resolver/framework/configstore.go
  pkg/resolver/framework/configstore_test.go
  pkg/resolver/framework/controller.go
  pkg/resolver/framework/interface.go
  pkg/resolver/framework/reconciler.go
  vendor/github.com/benbjohnson/clock/LICENSE
  vendor/github.com/benbjohnson/clock/README.md
  vendor/github.com/benbjohnson/clock/clock.go
  vendor/go.uber.org/zap/internal/ztest/clock.go
  vendor/go.uber.org/zap/internal/ztest/doc.go
  vendor/go.uber.org/zap/internal/ztest/timeout.go
  vendor/go.uber.org/zap/internal/ztest/writer.go
  vendor/go.uber.org/zap/zaptest/doc.go
  vendor/go.uber.org/zap/zaptest/logger.go
  vendor/go.uber.org/zap/zaptest/testingt.go
  vendor/go.uber.org/zap/zaptest/timeout.go
  vendor/go.uber.org/zap/zaptest/writer.go
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/modules.txt
Labels: kind/feature, size/XXL
